=== hakusone/cooking-club-site/clubServer/memberSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "id": "",
    "title": "Member format base",
    "descriptions": "Member format for import and export. By Sharon Wong",
    "type": "object",
    "properties": {
        "_id": {
            "type": "string"
        },
        "firstName": {
            "type": "string",
            "minLength": 1,
            "maxLength": 40
        },
        "lastName": {
            "type": "string",
            "minLength": 1,
            "maxLength": 40
        },
        "email": {
            "type": "string",
            "format": "email"
        },
        "role": {
            "type": "string",
            "enum": ["member", "admin"]
        },
        "password": {
            "type": "string"
        }
    },
    "required": ["firstName", "lastName", "email", "role", "password"],
    "additionalProperties": false
}

=== hakusone/cooking-club-site/clubServer/clubUsersHash.json
[
  {
    "firstName": "Melia",
    "lastName": "Barker",
    "email": "tirrivees1820@outlook.com",
    "password": "$2a$13$3lMPtE7UntEHlr3k4GqTSeOn5kjCoTs9FG/bkzJeH3qE9UK7Rs1oW",
    "role": "admin"
  },
  {
    "firstName": "Demetrice",
    "lastName": "Parker",
    "email": "chihuahua1899@gmail.com",
    "password": "$2a$13$b8wHPXvPdRCf0N3oxoX.WuGOBIK5722J6kAL9GmgG.E.QPUe1tZTS",
    "role": "member"
  },
  {
    "firstName": "Ligia",
    "lastName": "Hudson",
    "email": "umbrate1989@yahoo.com",
    "password": "$2a$13$LXxnJaNsZdF1sbY3N.z6UukC73ihUzqFrX8L4ESEZYse7A1FH0EO2",
    "role": "member"
  },
  {
    "firstName": "Maisha",
    "lastName": "Hickman",
    "email": "bibiri1807@yandex.com",
    "password": "$2a$13$1EPmw21MDqijs4fKrtA2uOHGE3AHle1rSei3opNqRPmzLZFjFNJcC",
    "role": "member"
  },
  {
    "firstName": "Cythia",
    "lastName": "Park",
    "email": "biune1929@gmail.com",
    "password": "$2a$13$3qIpYlDtWASF5sF/wjym.OhCQ4hnKtGvoTIc.Z77O6woYEZyBzbVW",
    "role": "member"
  },
  {
    "firstName": "Arlie",
    "lastName": "Holt",
    "email": "aromatised1858@yandex.com",
    "password": "$2a$13$/R6X5S0eYZ2337oQkkIHKurfoBOwugYVuO27I2.9u9VwdwrrDpbYS",
    "role": "member"
  },
  {
    "firstName": "Andy",
    "lastName": "Morton",
    "email": "bayesian1899@outlook.com",
    "password": "$2a$13$2yRTC0LmtWlp8HkhkYw2P.rfcmy3nndTXDwJx76qU8joZjomQfdSe",
    "role": "member"
  },
  {
    "firstName": "Peg",
    "lastName": "Gardner",
    "email": "earrings1987@yandex.com",
    "password": "$2a$13$cT96.NKU7/qqJOvYA07M/..z8CzKILVXkZUxZsim5.o34RyKfz1CS",
    "role": "member"
  },
  {
    "firstName": "Noble",
    "lastName": "Wilder",
    "email": "facer1912@yandex.com",
    "password": "$2a$13$vcjcvA9e9cVr3j2PCoeeWeIlEVWpzqRDiDKZU0IpnlLC7TCRgixbm",
    "role": "member"
  },
  {
    "firstName": "Willow",
    "lastName": "Trevino",
    "email": "nodes1883@yahoo.com",
    "password": "$2a$13$YNe52gv/ZzMQwmRycoGQ1.xuQt4dv.DAc6Y0brmN/mE1l.gMptU3u",
    "role": "member"
  },
  {
    "firstName": "Corrinne",
    "lastName": "Curtis",
    "email": "boisset1829@live.com",
    "password": "$2a$13$yJD28wKuc2eSFZ4JBFzuBOoFNIjwFKVhhya3ZOXoydfAeJG1aMUm2",
    "role": "member"
  },
  {
    "firstName": "Joseph",
    "lastName": "Brock",
    "email": "utilizer1910@live.com",
    "password": "$2a$13$69Uuh3z7EXUMxq.IxkkNYeD1Gc/WO47Tijcl.kp56xbJeVbKJ1qg6",
    "role": "member"
  },
  {
    "firstName": "Daron",
    "lastName": "Stevens",
    "email": "pedocalcic1982@outlook.com",
    "password": "$2a$13$NiKMmGx3bIynnUpHETPg0.92EyAA1C8GoxfZx3lvslwLsNpHUkIm.",
    "role": "member"
  },
  {
    "firstName": "Anamaria",
    "lastName": "Grant",
    "email": "downtown1843@live.com",
    "password": "$2a$13$NMPAgZgw/yjcHMbTYT7SL.KyiWFkQ.FW3ITki4WaR9./9551ebS6q",
    "role": "member"
  },
  {
    "firstName": "Leonard",
    "lastName": "Shepherd",
    "email": "thrower1972@yahoo.com",
    "password": "$2a$13$pZi5fJnWbXqEYZXnU.NUWeNNRNCwPUNB7BqfFP6jZM5tIEdRZt3XK",
    "role": "member"
  },
  {
    "firstName": "Belia",
    "lastName": "Monroe",
    "email": "cranky1882@gmail.com",
    "password": "$2a$13$TLSDPPyK..Sx3/vzRKmBN.LIujeznFrwwFmkp4uK2t5QXfnmr9nme",
    "role": "member"
  },
  {
    "firstName": "Stacey",
    "lastName": "Calderon",
    "email": "marsileaceae1910@gmail.com",
    "password": "$2a$13$iGGi3yoxbp7K7MOUt7zM4O935qFl/SZ9B4jpBO937XLrZMV/AlM7i",
    "role": "member"
  },
  {
    "firstName": "Bob",
    "lastName": "Fitzgerald",
    "email": "burin1898@yahoo.com",
    "password": "$2a$13$oCbDEGDpf3Z2anXTy4frRu7to3flCChDw7aIVTKCyt0F01FBIuEWK",
    "role": "member"
  },
  {
    "firstName": "Albertina",
    "lastName": "Mclaughlin",
    "email": "drainpipe2041@yandex.com",
    "password": "$2a$13$UWg0e9xsv6FuLYRVa9HaEe7POTgutJHLShaelb/QiDvGZ/Im9Kzv6",
    "role": "member"
  },
  {
    "firstName": "Marg",
    "lastName": "Carney",
    "email": "ventages2031@yahoo.com",
    "password": "$2a$13$1QQN.y3x6VyV/SBzH97ocely251U686AmInaqhJ29mXXKlv6qVxSy",
    "role": "member"
  },
  {
    "firstName": "Jeffery",
    "lastName": "Charles",
    "email": "zaffer1889@live.com",
    "password": "$2a$13$gnXL322hs2Qni/OqJiHlGOAJiJwELxqiHHfIUO3.niV9oHxkBC.rm",
    "role": "member"
  },
  {
    "firstName": "Annett",
    "lastName": "Parsons",
    "email": "kurikata1944@yandex.com",
    "password": "$2a$13$LaHn9bFpfS.kZeQMzru9aeHNvzSg2pXHkk5ooveH.X9YuCYqzsOES",
    "role": "member"
  },
  {
    "firstName": "Wilson",
    "lastName": "Sharpe",
    "email": "misunderstandable1916@live.com",
    "password": "$2a$13$qWtFHw.HacrTzCZcCMBjA.4w70uZbvKYqw/vcNw6cTVWNyZz0mkBy",
    "role": "member"
  },
  {
    "firstName": "Gertude",
    "lastName": "Ewing",
    "email": "althein1801@yahoo.com",
    "password": "$2a$13$5dOBLHXxuaMiJhc/.H5cS.BVoyznrxG5EMdNiNf7Y28skX97H2hq.",
    "role": "member"
  },
  {
    "firstName": "Phil",
    "lastName": "Knowles",
    "email": "piscators1880@live.com",
    "password": "$2a$13$b93/bTa2UiWOitTZANdLYuDN8ToV3UuPv.nzTZK2WnO.QsQzMtK3S",
    "role": "member"
  },
  {
    "firstName": "Catherina",
    "lastName": "Castillo",
    "email": "saltworker1892@live.com",
    "password": "$2a$13$uvbeq6eKE.8AqYxM7zxKsOV1whO1Yxaa7tWTB5brWtCo5c2pAMHNa",
    "role": "member"
  },
  {
    "firstName": "Jim",
    "lastName": "Kennedy",
    "email": "speer2026@outlook.com",
    "password": "$2a$13$iOazvKjIaAhQTRw4t9kZy.FpXcrseMScN5j/X96ZPp7Ws8IHrM04e",
    "role": "member"
  },
  {
    "firstName": "Tula",
    "lastName": "Stafford",
    "email": "devoir1853@live.com",
    "password": "$2a$13$6Kl/O4R5j5HvpDGwPiJgA.UE.xQeRgnWO1daqN.bJ0m5nELjYk70e",
    "role": "member"
  },
  {
    "firstName": "Rachell",
    "lastName": "Harding",
    "email": "article1896@outlook.com",
    "password": "$2a$13$Iqln09H40hw73lhWcM/nOu.CWlGKdewZQ0Q33JGU4v0g4hBnApyOK",
    "role": "member"
  },
  {
    "firstName": "Brandon",
    "lastName": "Monroe",
    "email": "article1821@live.com",
    "password": "$2a$13$ipimHHXXONX3GAO9LSYns.Bqyr644AxrRgk7WaJhGelBCtclZ4Aqi",
    "role": "member"
  },
  {
    "firstName": "Micha",
    "lastName": "Sanders",
    "email": "fewer1818@outlook.com",
    "password": "$2a$13$2eEemnk3qXqoUDPYM2NQ2OkddFUAApU6rlq3NMxOPG8KHyxCFOTn6",
    "role": "member"
  },
  {
    "firstName": "Blake",
    "lastName": "Gray",
    "email": "occults1985@yandex.com",
    "password": "$2a$13$2xtCrHF7N2/E8jinmBN1YuREsv.WxgAx6mR7.WyWat3Egg1I65CHW",
    "role": "member"
  },
  {
    "firstName": "Karren",
    "lastName": "Crosby",
    "email": "harborers2000@live.com",
    "password": "$2a$13$EnE0WnHeb5ORSwlffQeOBeM.f9RNvflfj8e.69sxIh9YL7EJwXeCy",
    "role": "member"
  },
  {
    "firstName": "Faustino",
    "lastName": "Morris",
    "email": "bayard1928@outlook.com",
    "password": "$2a$13$GzzOpR0RGAnvDv2VZfoOV.pEKQJI//RaaXIjpzc2PBLxINwu/Q1gi",
    "role": "member"
  },
  {
    "firstName": "Claretta",
    "lastName": "Cummings",
    "email": "fish2004@gmail.com",
    "password": "$2a$13$Cq06zhpIE/JGXMkfpSVTCu8GKCwJRyE9/h6Qn4nttBAYnTT2zQQUW",
    "role": "member"
  },
  {
    "firstName": "Carmen",
    "lastName": "Phillips",
    "email": "geometry1853@live.com",
    "password": "$2a$13$1e7h0SzaWKzAokCetHuqBOW26PGxwnrTicTP.ksTYdqn3NISddkta",
    "role": "member"
  },
  {
    "firstName": "Pamula",
    "lastName": "Holt",
    "email": "amperage1914@yandex.com",
    "password": "$2a$13$a/BjnSseQzj3AZRvaAPp.uI4TVpxO6Gcmc5Zxuo1SQUPdHuwrXHc2",
    "role": "member"
  },
  {
    "firstName": "Truman",
    "lastName": "Boyd",
    "email": "dustman2024@live.com",
    "password": "$2a$13$BdzgQWUGOv9NtjpVBcwWo.fjw0wJk/xu96Q6kVO79pnLHxgHonZ2a",
    "role": "member"
  },
  {
    "firstName": "Alphonso",
    "lastName": "Salazar",
    "email": "raddle2043@yandex.com",
    "password": "$2a$13$ke6NflI32pdam/uK00o2DeWZ3Jcs7kgogJPn0IDX/lxr20nAJyG.C",
    "role": "member"
  },
  {
    "firstName": "Isidra",
    "lastName": "O'neal",
    "email": "antonin2059@yahoo.com",
    "password": "$2a$13$Ak9/kgp65MrpEtBbthIPWej8newccWPKjcGwxiAPkAT/QPzHtExSK",
    "role": "member"
  }
]
